// 這裡是你專屬的序號資料庫，以後只要改這個檔案就好！
const sharedKeys = [
            "WWMREDDIT0625",
            "XRKPY6C38A",
            "EKNAPHAHYY",
            "WK7K8RY8JJ",
            "QTNJP7P4PC",
            "SY3KQQE8KR",
            "TPCF3FEN6Y",
            "NK4AJFPDWC",
            "JJXDTKCD8Y",
            "swcqqqhwae",
            "KPC346C44A",
            "PJCXEP4MFT",
            "FHHXEYRJAN",
            "APE6NNXY4K",
            "NDETCQEXHF",
            "CP8WMH8W4C",
            "XM8AQFRCPX",
            "QSFXR8EE8D",
            "MQECJKF7AR",
            "TP78EF43YH",
];
